import type { Metadata } from 'next';
import './globals.css';
export const metadata: Metadata = {
    title: 'My New App',
    description: 'Generated by Onlook',
};
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="mo--c47">
            <head>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
            </head>
            <body className="" data-oid="lq2kii0">
                {children}
            </body>
        </html>
    );
}
